require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StockBoxesController do

  # This should return the minimal set of attributes required to create a valid
  # StockBox. As you add validations to StockBox, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "number" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StockBoxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stock_boxes as @stock_boxes" do
      stock_box = StockBox.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stock_boxes).should eq([stock_box])
    end
  end

  describe "GET show" do
    it "assigns the requested stock_box as @stock_box" do
      stock_box = StockBox.create! valid_attributes
      get :show, {:id => stock_box.to_param}, valid_session
      assigns(:stock_box).should eq(stock_box)
    end
  end

  describe "GET new" do
    it "assigns a new stock_box as @stock_box" do
      get :new, {}, valid_session
      assigns(:stock_box).should be_a_new(StockBox)
    end
  end

  describe "GET edit" do
    it "assigns the requested stock_box as @stock_box" do
      stock_box = StockBox.create! valid_attributes
      get :edit, {:id => stock_box.to_param}, valid_session
      assigns(:stock_box).should eq(stock_box)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StockBox" do
        expect {
          post :create, {:stock_box => valid_attributes}, valid_session
        }.to change(StockBox, :count).by(1)
      end

      it "assigns a newly created stock_box as @stock_box" do
        post :create, {:stock_box => valid_attributes}, valid_session
        assigns(:stock_box).should be_a(StockBox)
        assigns(:stock_box).should be_persisted
      end

      it "redirects to the created stock_box" do
        post :create, {:stock_box => valid_attributes}, valid_session
        response.should redirect_to(StockBox.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stock_box as @stock_box" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockBox.any_instance.stub(:save).and_return(false)
        post :create, {:stock_box => { "number" => "invalid value" }}, valid_session
        assigns(:stock_box).should be_a_new(StockBox)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockBox.any_instance.stub(:save).and_return(false)
        post :create, {:stock_box => { "number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stock_box" do
        stock_box = StockBox.create! valid_attributes
        # Assuming there are no other stock_boxes in the database, this
        # specifies that the StockBox created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StockBox.any_instance.should_receive(:update_attributes).with({ "number" => "MyString" })
        put :update, {:id => stock_box.to_param, :stock_box => { "number" => "MyString" }}, valid_session
      end

      it "assigns the requested stock_box as @stock_box" do
        stock_box = StockBox.create! valid_attributes
        put :update, {:id => stock_box.to_param, :stock_box => valid_attributes}, valid_session
        assigns(:stock_box).should eq(stock_box)
      end

      it "redirects to the stock_box" do
        stock_box = StockBox.create! valid_attributes
        put :update, {:id => stock_box.to_param, :stock_box => valid_attributes}, valid_session
        response.should redirect_to(stock_box)
      end
    end

    describe "with invalid params" do
      it "assigns the stock_box as @stock_box" do
        stock_box = StockBox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StockBox.any_instance.stub(:save).and_return(false)
        put :update, {:id => stock_box.to_param, :stock_box => { "number" => "invalid value" }}, valid_session
        assigns(:stock_box).should eq(stock_box)
      end

      it "re-renders the 'edit' template" do
        stock_box = StockBox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StockBox.any_instance.stub(:save).and_return(false)
        put :update, {:id => stock_box.to_param, :stock_box => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stock_box" do
      stock_box = StockBox.create! valid_attributes
      expect {
        delete :destroy, {:id => stock_box.to_param}, valid_session
      }.to change(StockBox, :count).by(-1)
    end

    it "redirects to the stock_boxes list" do
      stock_box = StockBox.create! valid_attributes
      delete :destroy, {:id => stock_box.to_param}, valid_session
      response.should redirect_to(stock_boxes_url)
    end
  end

end
